# Generated by Django 4.2.9 on 2026-05-22 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('message_type', models.CharField(choices=[('text', 'Text Message'), ('template', 'Template Message'), ('media', 'Media Message')], default='text', max_length=20)),
                ('message_body', models.TextField(blank=True, help_text='Message text or template components')),
                ('template_name', models.CharField(blank=True, max_length=100)),
                ('template_language', models.CharField(default='en_US', max_length=10)),
                ('media_url', models.URLField(blank=True)),
                ('media_type', models.CharField(blank=True, choices=[('image', 'Image'), ('document', 'Document'), ('video', 'Video')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('queued', 'Queued'), ('sending', 'Sending'), ('completed', 'Completed'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('schedule_time', models.DateTimeField(blank=True, null=True)),
                ('total_recipients', models.IntegerField(default=0)),
                ('sent_count', models.IntegerField(default=0)),
                ('delivered_count', models.IntegerField(default=0)),
                ('read_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_groups', models.ManyToManyField(blank=True, related_name='campaigns', to='contacts.contactgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CampaignRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('wam_id', models.CharField(blank=True, max_length=100, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='campaigns.campaign')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='contacts.contact')),
            ],
            options={
                'verbose_name': 'Campaign Recipient',
                'verbose_name_plural': 'Campaign Recipients',
                'ordering': ('-created_at',),
                'unique_together': {('campaign', 'contact')},
            },
        ),
    ]
